name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Update Go modules
        run: go mod tidy

      - name: Commit changes if needed
        run: |
          if [[ -n $(git status -s) ]]; then
            git config --global user.email "github-actions@github.com"
            git config --global user.name "GitHub Actions"
            git add go.mod go.sum
            git commit -m "chore: update go.mod and go.sum" || echo "No changes to commit"
            
            # Force update the tag to point to the new commit
            git tag -f ${GITHUB_REF#refs/tags/}
            git push --force origin ${GITHUB_REF#refs/tags/}
          fi

      - name: Validate GoReleaser Config
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: check

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          SCOOP_BUCKET_GITHUB_TOKEN: ${{ secrets.SCOOP_BUCKET_GITHUB_TOKEN }}
          CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
